### ISSUE TITLE
Missing template to render

### ISSUE THREAD

**Issue by gymgnopf** [cvergne/vscode-php-getters-setters#14] opened 2021-11-19 13:46 UTC
Hey thank you for your awesome work. 

After updating to version 1.4, I get the error 'Missing template to render', when I click on 'Insert all PHP Getter & Setter'.
I dont use custom templates, but I checked the folder '%APPDATA%\Code\User\phpGettersSetters' and didn't see any template files. 

'Insert PHP Getter & Setter' works just fine. 

Thank you for looking at it.

**Comment by cvergne** [comment] 2021-11-19 14:39
Hi,

That is strange because all commands are using the same render method.
I neither have any template file and it's working fine.

Did you try to restart VSCode ?
The bug is on any file ? Could you give an example ?

**Comment by cvergne** [comment] 2021-11-19 14:40
Also could you send a screenshot of your extension settings ? (you can right click on the extension in the sidebar then "Extension Settings".

**Comment by gymgnopf** [comment] 2021-11-22 09:39
Hi, thank you for your answer.
I did restart VSCode but the problem is still there.

![error-message](https://user-images.githubusercontent.com/62284256/142836866-a7b4dd1c-c0a0-4c9b-b45c-2ef70955c328.png)
.
![settings](https://user-images.githubusercontent.com/62284256/142837096-5216bd53-9214-4d1b-a68a-877ed95c4eea.png)

I hope this is helpful.

**Comment by cvergne** [comment] 2021-11-22 12:36
Everything seems normal at this point.
Do you have `phpGettersSetters.templatesDir` in `settings.json`? (if you click on "Edit in settings.json")

**Comment by gymgnopf** [comment] 2021-11-22 16:18
No, there was no entry.

**Comment by alcalyn** [comment] 2022-02-17 09:43
Same here, works for "Insert PHP getter", "Insert PHP setter", "Insert PHP getter & setter", **but** does not works for "Insert ALL PHP getter & setter".

I tried to define a `phpGettersSetters.templatesDir` with my custom getter and setter templates, but I get same result.

**Comment by cvergne** [comment] 2022-02-17 09:59
@alcalyn Do you have an example of PHP code not working on your side please ? :)

**Comment by alcalyn** [comment] 2022-02-17 16:16
Sure, I can reproduce it with a very simple class:

``` php
<?php

class Hello
{
    private int $number;

    private DateTime $date;
}
```

**Comment by cvergne** [comment] 2022-04-27 12:52
So, should be fixed on v1.6.0. Thanks :)

**Closed by cvergne** 2022-04-27 12:52 UTC
